name: Release
on:
  push:
    # branches:
    #   - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "tudelft-report.zip"
          exclusions: >
            *.git/*
            *.github/*
            /*.vscode/*
            /*design/*
            /*src/*
            /*build/*
            build.lua
            .gitignore
            LICENSE
            README.md
      - name: Create prerelease
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tudelft-report.zip,report.pdf"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
