name: Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "tudelft-report.zip"
          exclusions: >
            *.git/*
            *.github/*
            .vscode/*
            /*design/*
            .gitignore
            LICENSE
            README.md
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tudelft-report.zip"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
